
/************************************
* INERST DATA
************************************/

/*
COMMON_LOOKUP INSERTS
*/
INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'SYSTEM_USER'
    , 'FK_SYSTEM_USER_TYPE'
    , 'System User'
    , 1
    , 'System User'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'CONTACT'
    , 'FK_CONTACT_TYPE'
    , 'Contact Type'
    , 'CT'
    , 'Customer'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'CONTACT'
    , 'FK_DEFAULT_CONTACT_METHOD'
    , 'Contact Method'
    , 'CM'
    , 'Phone'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'CONTACT'
    , 'FK_DEFAULT_CONTACT_METHOD'
    , 'Contact Method'
    , 'CM'
    , 'Email'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'CONTACT'
    , 'FK_DEFAULT_CONTACT_METHOD'
    , 'Contact Method'
    , 'CM'
    , 'Mail'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'PROJECT'
    , 'FK_SEVERITY'
    , 'Severity'
    , 1
    , 'One'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'PROJECT'
    , 'FK_SEVERITY'
    , 'Severity'
    , 2
    , 'Two'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

INSERT INTO COMMON_LOOKUP(
      COMMON_LOOKUP_ID 
    , COMMON_LOOKUP_TABLE 
    , COMMON_LOOKUP_COLUMN 
    , COMMON_LOOKUP_TYPE 
    , COMMON_LOOKUP_CODE 
    , COMMON_LOOKUP_MEANING 
    , CREATED_BY
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE
)
VALUES(
      common_lookup_s1.NEXTVAL
    , 'PROJECT'
    , 'FK_SEVERITY'
    , 'Severity'
    , 3
    , 'Three'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

/*
SYSTEM_USER INSERTS
*/

INSERT INTO SYSTEM_USER(
    SYSTEM_USER_ID
    , SYSTEM_USER_NAME
    , FK_CONTACT_ID
    , FK_SYSTEM_USER_TYPE
    , CREATED_BY
    , CREATION_DATE
    , LAST_UPDATED_BY
    , LAST_UPDATED_DATE) 
VALUES(
      system_user_s1.NEXTVAL
    , 'SYSTEM'
    , 1
    , 1
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

/*
CONTACT INSERTS
*/

INSERT INTO CONTACT(
      CONTACT_ID
    , FK_CONTACT_TYPE 
    , LAST_NAME 
    , FIRST_NAME 
    , PRIMARY_PHONE 
    , SECONDARY_PHONE 
    , ADDRESS 
    , EMAIL 
    , FK_DEFAULT_CONTACT_METHOD
    , CREATED_BY
    , CREATION_DATE
    , LAST_UPDATED_BY
    , LAST_UPDATED_DATE)
VALUES(
      contact_s1.NEXTVAL
    , (SELECT COMMON_LOOKUP_ID FROM COMMON_LOOKUP WHERE COMMON_LOOKUP_MEANING = 'Customer')
    , 'Rob'
    , 'Page'
    , '12082065802'
    ,  NULL
    , '3727 West Mountain View Drive Rexburg, ID 83440'
    , 'pager925@gmail.com'
    , (SELECT COMMON_LOOKUP_ID FROM COMMON_LOOKUP WHERE COMMON_LOOKUP_MEANING = 'Phone')
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

ALTER TABLE SYSTEM_USER ADD CONSTRAINT fk2_system_user
FOREIGN KEY (FK_CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);


/*
PROJECT INSERTS
*/

INSERT INTO PROJECT(
      PROJECT_ID 
    , FK_CONTACT_ID 
    , FK_SYSTEM_USER_ID 
    , FK_SEVERITY 
    , DUE_DATE 
    , NEXT_RESPONSE_DUE 
    , CREATED_BY 
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE)
VALUES(
      project_s1.NEXTVAL
    , (SELECT CONTACT_ID FROM CONTACT WHERE PRIMARY_PHONE = '12082065802')
    , (SELECT SYSTEM_USER_ID FROM SYSTEM_USER WHERE SYSTEM_USER_ID  = 1)
    , (SELECT COMMON_LOOKUP_ID FROM COMMON_LOOKUP WHERE COMMON_LOOKUP_MEANING = 'One')
    , SYSDATE
    , SYSDATE
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

/*
INTERACTION INSERTS
*/

INSERT INTO INTERACTION(
      INTERACTION_ID
    , FK_SYSTEM_USER_ID 
    , FK_CONTACT_ID 
    , FK_INTERACTION_TYPE 
    , INTERACTION_SOURCE_OBJECT
    , CREATED_BY 
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE)
VALUES(
      interaction_s1.NEXTVAL
    , (SELECT SYSTEM_USER_ID FROM SYSTEM_USER WHERE SYSTEM_USER_ID = 1)
    , (SELECT CONTACT_ID FROM CONTACT WHERE CONTACT_ID = 1)
    , (SELECT COMMON_LOOKUP_ID FROM COMMON_LOOKUP WHERE COMMON_LOOKUP_MEANING = 'Phone')
    , 'njkjn'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);

/*
INTER_PRO_JUNC INSERTS
*/


INSERT INTO INTER_PRO_JUNC(
          INTER_PRO_JUNC_ID 
        , FK_INTERACTION_ID 
        , FK_PROJECT_ID)
VALUES(
      inter_pro_junc_s1.NEXTVAL
    , (SELECT INTERACTION_ID FROM INTERACTION WHERE INTERACTION_ID = 1)
    , (SELECT PROJECT_ID FROM PROJECT WHERE PROJECT_ID = 1)
);

/*
MESSAGE INSERTS
*/

INSERT INTO MESSAGE(
     MESSAGE_ID 
    , FK_INTERACTION_ID 
    , MESSAGE 
    , CREATED_BY 
    , CREATION_DATE 
    , LAST_UPDATED_BY 
    , LAST_UPDATED_DATE)
VALUES(
      message_s1.NEXTVAL
    , (SELECT INTERACTION_ID FROM INTERACTION WHERE INTERACTION_ID = 1)
    , 'TEST MESSAGE ON FIRST INTERACTION'
    , 1
    , SYSDATE
    , 1
    , SYSDATE
);